spring:
  application:
    name: greeting-service

management:
  endpoint:
  endpoints:
    web:
      exposure:
        include:
          - '*'

greeting-service:
  greeting: "Ciao"
  default-value: "Mondo"
